### ISSUE TITLE
how 3 windows

### ISSUE THREAD

**Issue by EinfachAlex** [Jerrynicki/jrery-bot#1]
se3rvus how do instal on windowws ?

**Comment by Jerrynicki** [comment]
install python >= 3.5 from https://python.org (make sure to add it to your PATH), `py -m pip install discord.py[voice] requests`, download https://www.datendieter.de/item/Liste_von_deutschen_Staedtenamen_.csv as staedte_osm.txt, download https://www.datendieter.de/item/Liste_von_deutschen_Strassennamen_.csv as strassen_osm.txt, write the config.json as `{"token": "bot token", "owner_id": "your discord id"}` and then run the bot with `py start.py`

**Comment by Jerrynicki** [comment]
many features will probably not work though, as the bot was coded with a unix-like os in mind
